spring:
  datasource:
    password: mpw:ZteSfG9AblmTE0fDykNImA== # 使用加密
    username: mpw:ZteSfG9AblmTE0fDykNImA== # 使用加密
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.liuxsen: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SS


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0 # 逻辑未删除值 0
      logic-delete-value: 1 # 逻辑已删除值 1
  configuration:
    # 配置枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

